title: Cherie Pavico-Tsukayama # your name (or website title) here
logo: "images/CheriePavicoTsukayama.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-Driven 📊 Marketing Creative 🎨 @ Voiceplace | Data Analytics | Data Visualization
  | SQL | Tableau | Excel | Kajabi Expert | HTML | CSS | JS  <br><br>
  <a href="https://www.linkedin.com/in/cheriepavico/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
